set -g @catppuccin_flavor 'cyberdream'
set -g @catppuccin_reset 'true'
run '~/.config/tmux/catppuccin-helpers/reset.sh'
run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'

# set other catppuccin options and run the plugin again according to docs: 
# https://github.com/catppuccin/tmux/blob/main/docs/tutorials/03-resetting-theme.md
set -g @catppuccin_flavor 'cyberdream'
set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_window_status 'no'
set -g @catppuccin_window_number_position 'right'
set -g @catppuccin_window_text '#W'
set -g @catppuccin_window_current_fill 'number'
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_current_color '#{E:@thm_surface_2}'
set -g @catppuccin_date_time_text '%d-%m-%y %H:%M'
set -g @catppuccin_status_module_text_bg '#{E:@thm_mantle}'

run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'
