set -g @catppuccin_flavor 'cyberdream'
set -g @catppuccin_reset 'true'
run '~/.config/tmux/catppuccin-helpers/reset.sh'
run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'

# set @sessionx-additional-options with dark-themed fzf colors to match cyberdream theme (bg:#16181a)
run 'tmux set-option -g @sessionx-additional-options "--color=bg:#16181a,fg:#ffffff,hl:#5ea1ff,bg+:#1e2124,fg+:#ffffff,hl+:#5ef1ff,header:#bd5eff,info:#7b8496,pointer:#5ef1ff,marker:#5eff6c,spinner:#5ef1ff,prompt:#5ea1ff,query:#ffffff"'

# set other catppuccin options and run the plugin again according to docs: 
# https://github.com/catppuccin/tmux/blob/main/docs/tutorials/03-resetting-theme.md
set -g @catppuccin_flavor 'cyberdream'
set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_window_status 'no'
set -g @catppuccin_window_number_position 'right'
set -g @catppuccin_window_text '#W'
set -g @catppuccin_window_current_fill 'number'
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_current_color '#{E:@thm_surface_2}'
set -g @catppuccin_date_time_text '%d-%m-%y %H:%M'
set -g @catppuccin_status_module_text_bg '#{E:@thm_mantle}'

run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'
