set -g @catppuccin_flavor 'cyberdreamlight'
set -g @catppuccin_reset 'true'
run '~/.config/tmux/catppuccin-helpers/reset.sh'
run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'

# set @sessionx-additional-options with light-themed fzf colors to match cyberdreamlight theme (bg:#ffffff)
run 'tmux set-option -g @sessionx-additional-options "--color=bg:#ffffff,fg:#16181a,hl:#0057d1,bg+:#eaeaea,fg+:#16181a,hl+:#008c99,header:#a018ff,info:#7b8496,pointer:#008c99,marker:#008b0c,spinner:#008c99,prompt:#0057d1,query:#16181a"'

# set other catppuccin options and run the plugin again according to docs: 
# https://github.com/catppuccin/tmux/blob/main/docs/tutorials/03-resetting-theme.md
set -g @catppuccin_flavor 'cyberdreamlight'
set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_window_status 'no'
set -g @catppuccin_window_number_position 'right'
set -g @catppuccin_window_text '#W'
set -g @catppuccin_window_current_fill 'number'
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_current_color '#{E:@thm_surface_2}'
set -g @catppuccin_date_time_text '%d-%m-%y %H:%M'
set -g @catppuccin_status_module_text_bg '#{E:@thm_mantle}'

run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'
